### ISSUE TITLE
dline freezes when "/dm" command is called

### ISSUE THREAD

**Issue by JushBJJ** [NatTupper/dline#17] opened 2019-01-02 13:58 UTC
Python Version: Python3.6
Terminal: uxrvt
Shell: bash

When I type in the command 

> /dm

or 
> /guild Private Messages 

Or anything similar freezes dline, and the issue is on the Mee6 bot which is quite weird for it to effect dline like that. A few months back me and Nat did a little test on reproducing the freeze. But it seems Nat's dm works even with mee6 on it.

**Comment by NatTupper** [comment] 2019-02-03 17:03
Will look into

**Comment by NatTupper** [comment] 2019-02-04 09:11
Tested and could not reproduce. Closing for now. If you have another method to reproduce, reopen the issue.

**Closed by NatTupper** 2019-02-04 09:11 UTC
Labels: looking into
